/**
 * PDF Export Utility
 *
 * Converts a CRO idea card into a PDF download using jsPDF + html2canvas.
 */

import jsPDF from "jspdf";
import html2canvas from "html2canvas";

export async function exportIdeaToPDF(idea: {
  title: string;
  description: string;
  reason: string;
  purpose: string;
  category: { name: string };
  mockupUrl: string | null;
}): Promise<void> {
  // Create a temporary DOM element to render the card
  const element = document.createElement("div");
  element.style.cssText = `
    position: fixed;
    top: -9999px;
    left: -9999px;
    width: 800px;
    padding: 40px;
    background: #ffffff;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    color: #1a1a1a;
  `;

  const categoryColor = "#2189FF";
  const accentColor = "#10b981";

  element.innerHTML = `
    <div style="border-radius: 16px; overflow: hidden; border: 1px solid #e5e7eb; background: #fff;">
      ${idea.mockupUrl ? `
        <div style="aspect-ratio: 16/9; overflow: hidden; background: #f3f4f6;">
          <img src="${idea.mockupUrl}" style="width: 100%; height: 100%; object-fit: cover;" />
        </div>
      ` : `
        <div style="aspect-ratio: 16/9; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); display: flex; align-items: center; justify-content: center; color: white; font-size: 14px;">
          No mockup image
        </div>
      `}
      <div style="padding: 32px;">
        <span style="display: inline-block; padding: 4px 12px; border-radius: 9999px; font-size: 11px; font-weight: 600; background: ${categoryColor}20; color: ${categoryColor}; margin-bottom: 12px;">
          ${idea.category.name}
        </span>
        <h1 style="font-size: 24px; font-weight: 700; margin: 0 0 12px 0; color: #111827; line-height: 1.3;">
          ${idea.title}
        </h1>
        <p style="font-size: 14px; color: #6b7280; line-height: 1.6; margin: 0 0 24px 0;">
          ${idea.description}
        </p>
        <div style="border-top: 1px solid #e5e7eb; padding-top: 24px; display: flex; flex-direction: column; gap: 20px;">
          <div>
            <h2 style="font-size: 13px; font-weight: 600; color: #374151; margin: 0 0 8px 0; display: flex; align-items: center; gap: 6px;">
              <span style="color: ${accentColor};">●</span> Why this works
            </h2>
            <p style="font-size: 13px; color: #6b7280; line-height: 1.6; margin: 0;">
              ${idea.reason}
            </p>
          </div>
          <div>
            <h2 style="font-size: 13px; font-weight: 600; color: #374151; margin: 0 0 8px 0; display: flex; align-items: center; gap: 6px;">
              <span style="color: ${categoryColor};">●</span> Purpose
            </h2>
            <p style="font-size: 13px; color: #6b7280; line-height: 1.6; margin: 0;">
              ${idea.purpose}
            </p>
          </div>
        </div>
      </div>
    </div>
    <div style="margin-top: 16px; text-align: center; font-size: 11px; color: #9ca3af;">
      Generated by CRO Ideas Board
    </div>
  `;

  document.body.appendChild(element);

  try {
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      allowTaint: true,
      backgroundColor: "#ffffff",
    });

    const imgData = canvas.toDataURL("image/png");
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "px",
      format: [canvas.width / 2, canvas.height / 2],
    });

    pdf.addImage(imgData, "PNG", 0, 0, canvas.width / 2, canvas.height / 2);
    pdf.save(`${idea.title.replace(/[^a-z0-9]/gi, "-").toLowerCase()}.pdf`);
  } finally {
    document.body.removeChild(element);
  }
}